/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.58
 * Generated at: 2022-03-20 07:02:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class insertUserPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/views/login/../common/footer.jsp", Long.valueOf(1646494339491L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>회원가입</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../../resources/css/common/common.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../../resources/css/sign-upPage.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <header id=\"header\">\r\n");
      out.write("        <div id=\"logo\">\r\n");
      out.write("            <a href=\"/\"><img src=\"../../resources/images/logo.gif\" alt=\"로고이미지\"></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <span id=\"page_title\">간편 회원가입</span>\r\n");
      out.write("    </header>\r\n");
      out.write("    <div id=\"input_container\">\r\n");
      out.write("        <form id=\"input_box\" action=\"");
      out.print(request.getContextPath() );
      out.write("/insertUser\" method=\"post\">\r\n");
      out.write("        \r\n");
      out.write("            <div class=\"content_box\">\r\n");
      out.write("                <div class=\"id_input\">\r\n");
      out.write("                    <input class=\"input\" type=\"text\" name=\"userId\" placeholder=\"아이디\" required>\r\n");
      out.write("                    <button id=\"userIdCheck\" class=\"input\" type=\"button\">중복확인</button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <input type=\"password\" name=\"userPwd\" placeholder=\"비밀번호\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <input type=\"password\" name=\"userPwdCheck\" placeholder=\"비밀번호확인\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <input type=\"text\" name=\"name\" placeholder=\"이름\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <input type=\"text\" name=\"citiNumber\" placeholder=\"주민등록번호(-없이)\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <input type=\"text\" name=\"phone\" placeholder=\"전화번호(-없이)\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <input type=\"text\" name=\"nickName\" placeholder=\"닉네임\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <input type=\"text\" name=\"email\" placeholder=\"이메일\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <input id=\"male\" type=\"radio\" name=\"gender\" value=\"M\" checked><label for=\"male\">남자</label>\r\n");
      out.write("                    <input id=\"female\" type=\"radio\" name=\"gender\" value=\"F\"><label for=\"female\">여자</label>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <input id=\"consent\" type=\"checkbox\" name=\"consent\" required><label for=\"consent\">개인정보제공 동의</label>\r\n");
      out.write("                    <textarea cols=\"36\" rows=\"10\" readonly>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi consequatur exercitationem quis, ratione ad dolor tempore corrupti omnis atque nisi necessitatibus animi, ex molestias laudantium voluptas praesentium! Officiis, blanditiis praesentium. Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit perferendis, facilis officia quidem dolorum minus in molestiae odit quis eaque, molestias eius modi dicta earum quos voluptas tenetur illum itaque. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ea corrupti necessitatibus id veniam quas eos, corporis sit repudiandae, esse animi aspernatur modi asperiores laudantium impedit, tenetur laborum cumque quisquam at. Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores, obcaecati? Nobis, consectetur? Dolores officiis, similique rerum nisi voluptas odit reiciendis architecto veritatis neque rem tempora harum voluptatem molestiae, facere quo!</textarea>\r\n");
      out.write("                </div>\r\n");
      out.write("                <button type=\"submit\" class=\"button\">다음</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("    <!DOCTYPE html>\r\n");
      out.write("    <html lang=\"en\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("        <title>Document</title>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"../../resources/css/common/common.css\">\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        <footer id=\"footer\">\r\n");
      out.write("            <div id=\"footer_content\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <span>발표시키지마시조</span>\r\n");
      out.write("                    |\r\n");
      out.write("                    <span>팀장 : 노한서</span>\r\n");
      out.write("                    |\r\n");
      out.write("                    <span>팀원 : 조현</span>\r\n");
      out.write("                    |\r\n");
      out.write("                    <span>팀원 : 김태연</span>\r\n");
      out.write("                    |\r\n");
      out.write("                    <span>팀원 : 최윤종</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <span>세미 프로젝트</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <span>노한서(팀장) : </span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <span>조현 : </span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <span>김태연 : </span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <span>최윤종 : </span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <span>Copyright © 2022.02.22-2022.04.03 KH Information Educational Institute All Right Reserved</span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"logo\"><a href=\"/\"><img src=\"../../resources/images/logo.gif\" alt=\"로고이미지\"></a></div>\r\n");
      out.write("        </footer>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("        <script src=\"../../resources/library/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("        <script src=\"../../resources/js/common/common.js\"></script>\r\n");
      out.write("    </body>\r\n");
      out.write("    </html>");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("    <script src=\"../../resources/library/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("    <script src=\"../../resources/js/common/common.js\"></script>\r\n");
      out.write("    <script src=\"../../resources/js/sign-upPage.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
