/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.58
 * Generated at: 2022-03-20 07:35:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.service;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class serviceCenterEnrollForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/service/../common/header.jsp", Long.valueOf(1647761680253L));
    _jspx_dependants.put("/views/service/../common/footer.jsp", Long.valueOf(1647761680250L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../../resources/css/common/common.css\">\r\n");
      out.write("<style>\r\n");
      out.write("	/*전체 페이지 div*/\r\n");
      out.write("	.enrollForm1{\r\n");
      out.write("       	width:70%;\r\n");
      out.write("       	margin:0 auto;\r\n");
      out.write("       	height: 550px;\r\n");
      out.write("\r\n");
      out.write("      }\r\n");
      out.write("     /*header 글작성 글*/\r\n");
      out.write("     .headerenrollForm{\r\n");
      out.write("     	margin-top:2%;\r\n");
      out.write("     	font-size:30px;\r\n");
      out.write("     }\r\n");
      out.write("     /*글 작성 아래 라인*/\r\n");
      out.write("     .underheaderenrollF{\r\n");
      out.write("     	margin-top: 10px;\r\n");
      out.write("     	border-top: 2px solid black;\r\n");
      out.write("     }\r\n");
      out.write("     /*제목 div*/\r\n");
      out.write("     .enrollTitlesection{\r\n");
      out.write("     	height:50px;\r\n");
      out.write("     	line-height:50px;\r\n");
      out.write("		width:100%;\r\n");
      out.write("		display:flex;\r\n");
      out.write("		align-items: center;\r\n");
      out.write("		border-bottom:1px solid black;\r\n");
      out.write("     }\r\n");
      out.write("     .titleNamepart, .counttitlename, .counttitlelength{\r\n");
      out.write("     	width:100%;\r\n");
      out.write("     }\r\n");
      out.write("     /*counttitlename :제목 입력부분 */\r\n");
      out.write("     .counttitlename{\r\n");
      out.write("     	width : 40%;\r\n");
      out.write("     	padding-left: 12px;\r\n");
      out.write("		height:60%;\r\n");
      out.write("     }\r\n");
      out.write("     /*titleNamepart : 제목 글씨부분*/\r\n");
      out.write("     .titleNamepart{\r\n");
      out.write("     	font-size:19px;\r\n");
      out.write("     	width:18%;\r\n");
      out.write("     	height:50px;\r\n");
      out.write("     	margin:0 0 0 15px;\r\n");
      out.write("     	line-height:37px;\r\n");
      out.write("     	\r\n");
      out.write("     }\r\n");
      out.write("     /*dotpoint:*이부분 */\r\n");
      out.write("     .dotpoint{\r\n");
      out.write("     	color: red;\r\n");
      out.write("     	font-weight: 800;\r\n");
      out.write("     	font-size:20px;\r\n");
      out.write("     	vertical-align: 5px;\r\n");
      out.write("     }\r\n");
      out.write("     /*counttitlelength : count하는 부분*/\r\n");
      out.write("     .counttitlelength{\r\n");
      out.write("     	margin-left:15px;\r\n");
      out.write("     	height:70%;\r\n");
      out.write("     	width:30%;\r\n");
      out.write("     }\r\n");
      out.write("  		/*카테고리 select 부분*/\r\n");
      out.write("     .categoryList{\r\n");
      out.write("     	width: 200px; /* 가로 사이즈 */\r\n");
      out.write("	    padding: 8px; /* 내부여백 */\r\n");
      out.write("	    padding-left: 12px;\r\n");
      out.write("	    border: 1px solid #ddd;\r\n");
      out.write("	    background: url(./arrow_down_18dp.png) no-repeat right 50%; /* 화살표 위치 */\r\n");
      out.write("	    background-size: 30px; /* 화살표 크기 */\r\n");
      out.write("	    border-radius: 4px;\r\n");
      out.write("	    box-sizing: border-box;\r\n");
      out.write("	    font-size: 12px;\r\n");
      out.write("	    color: #000;\r\n");
      out.write("	    outline:none;\r\n");
      out.write("	    height:35px;\r\n");
      out.write("     }\r\n");
      out.write("     \r\n");
      out.write("     /*enrollcontentsection:내용 div 부분*/\r\n");
      out.write("     .enrollcontentsection{\r\n");
      out.write("     	display:flex;\r\n");
      out.write("     	margin-top:15px;\r\n");
      out.write("     }\r\n");
      out.write("   \r\n");
      out.write("     /*등록하기 버튼*/\r\n");
      out.write("     .gotoSubmitbutton, .gobackServiceCenterMain{\r\n");
      out.write("	    position: relative;\r\n");
      out.write("	    border: none;\r\n");
      out.write("	    display: inline-block;\r\n");
      out.write("	    padding: 10px 15px;\r\n");
      out.write("	    border-radius: 15px;\r\n");
      out.write("	    font-family: \"paybooc-Light\", sans-serif;\r\n");
      out.write("	    box-shadow: 0 15px 35px rgba(0, 0, 0, 0.2);\r\n");
      out.write("	    text-decoration: none;\r\n");
      out.write("	    font-weight: 600;\r\n");
      out.write("	    transition: 0.25s;\r\n");
      out.write("     	border: 2px solid #993333;\r\n");
      out.write("     	margin-top:15px;\r\n");
      out.write("    	color: black;\r\n");
      out.write("     }\r\n");
      out.write("     .gotoSubmitbutton:hover, .gobackServiceCenterMain:hover{\r\n");
      out.write("     	 background-color: #993333;\r\n");
      out.write("    	 color: white;\r\n");
      out.write("     }\r\n");
      out.write("     .countContentlength{\r\n");
      out.write("     	\r\n");
      out.write("     }\r\n");
      out.write("	\r\n");
      out.write("     \r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../../resources/css/common/common.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <header id=\"main_header\">\r\n");
      out.write("        <div id=\"header\">\r\n");
      out.write("            <div id=\"logo\"><a href=\"/\"><img src=\"../../resources/images/logo.gif\" alt=\"메인로고이미지\"></a></div>\r\n");
      out.write("            <div id=\"search\">\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"header_top_right\">\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/loginPage\" class=\"login_page\">로그인</a>\r\n");
      out.write("                /\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/sign_up\" class=\"insert_user\">회원가입</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <nav id=\"main_nav\">\r\n");
      out.write("            <div class=\"nav\">\r\n");
      out.write("                <div class=\"category\">\r\n");
      out.write("                    <div class=\"category_box\">\r\n");
      out.write("                        <i class=\"berger1\"></i>\r\n");
      out.write("                        <i class=\"berger2\"></i>\r\n");
      out.write("                        <i class=\"berger3\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><div onmouseover=\"add()\" onmouseleave=\"remove()\"><a href=\"<!--이동할 jsp가 위치한 경로입력 할 것-->\">시세</a></div></li>\r\n");
      out.write("                    <li><div onmouseover=\"add()\" onmouseleave=\"remove()\"><a href=\"<!--이동할 jsp가 위치한 경로입력 할 것-->\">경매</a></div></li>\r\n");
      out.write("                    <li><div onmouseover=\"add()\" onmouseleave=\"remove()\"><a href=\"<!--이동할 jsp가 위치한 경로입력 할 것-->\">커뮤니티</a></div></li>\r\n");
      out.write("                    <li><div onmouseover=\"add()\" onmouseleave=\"remove()\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/usedBoardList.do\">중고거래</a></div></li>\r\n");
      out.write("                    <li><div onmouseover=\"add()\" onmouseleave=\"remove()\"><a href=\"<!--이동할 jsp가 위치한 경로입력 할 것-->\">이벤트</a></div></li>\r\n");
      out.write("                    <li><div onmouseover=\"add()\" onmouseleave=\"remove()\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/serviceCenter.do\">고객센터</a></div></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("    <script src=\"../../resources/library/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("    <script src=\"../../resources/js/common/common.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("	<div class = \"enrollForm1\">\r\n");
      out.write("	<div class=\"headerenrollForm\"><!-- 고객센터 글 작성 위에 부분 -->\r\n");
      out.write("		<p> 고객센터 글 작성</p>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"underheaderenrollF\"></div><!-- 라인 부분 -->\r\n");
      out.write("	\r\n");
      out.write("	<form class=\"enrollServiceCenterForm\" action=\"");
      out.print(request.getContextPath());
      out.write("/insertServiceCenter.do\" method=\"post\">\r\n");
      out.write("	<div class=\"enrollTitlesection\"><!-- 제목 div -->\r\n");
      out.write("		<span class=\"titleNamepart\"> 제목<span class=\"dotpoint\">*</span></span>\r\n");
      out.write("		<input type=\"text\" name=\"title\" class=\"counttitlename\" placeholder=\"제목을 입력해주세요\" maxlength=\"40\" required>\r\n");
      out.write("		<span class=\"counttitlelength\">0 / 40</span>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"enrollTitlesection\"><!-- 카테고리 선택 div -->\r\n");
      out.write("		<span class=\"titleNamepart\"> 카테고리<span class=\"dotpoint\">*</span></span>\r\n");
      out.write("		<div class=\"categorytogglepart\">\r\n");
      out.write("			<select class=\"categoryList\" name=\"category\" required>\r\n");
      out.write("				<option class=\"optionlist\" value=1 selected>운영 정책</option>\r\n");
      out.write("				<option class=\"optionlist\" value=2>계정/인증</option>\r\n");
      out.write("				<option class=\"optionlist\" value=3>구매/판매</option>\r\n");
      out.write("				<option class=\"optionlist\" value=4>거래 품목</option>\r\n");
      out.write("				<option class=\"optionlist\" value=5>거래 매너</option>\r\n");
      out.write("				<option class=\"optionlist\" value=6>이벤트</option>\r\n");
      out.write("				<option class=\"optionlist\" value=7>이용 제재</option>\r\n");
      out.write("				<option class=\"optionlist\" value=8>커뮤니티</option>\r\n");
      out.write("				<option class=\"optionlist\" value=9>경매</option>\r\n");
      out.write("				<option class=\"optionlist\" value=10>채팅</option>\r\n");
      out.write("				<option class=\"optionlist\" value=11>기타</option>\r\n");
      out.write("			</select>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"enrollcontentsection\"><!-- 내용 작성 div -->\r\n");
      out.write("		<span class=\"titleNamepart\"> 글 내용<span class=\"dotpoint\">*</span></span>\r\n");
      out.write("		<div class=\"contentpart\">\r\n");
      out.write("			<textarea name =\"content\" class=\"contentWritePart\" cols=\"70\" rows=\"15\" style=\"resize:none;\" required></textarea>\r\n");
      out.write("		</div>\r\n");
      out.write("		<span class=\"countContentlength\">0 / 2000</span>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"deleteorsubmit\" align=\"right\"><!-- 삭제, 등록버튼 -->\r\n");
      out.write("		<button type=\"submit\" class=\"gotoSubmitbutton\"> 등록하기 </button>\r\n");
      out.write("		<button type=\"button\" class=\"gobackServiceCenterMain\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/serviceCenter.do'\"> 취소하기 </button>\r\n");
      out.write("	</div>\r\n");
      out.write("	</form>\r\n");
      out.write("	\r\n");
      out.write("	</div>\r\n");
      out.write("	<script>\r\n");
      out.write("		//제목 40자 미만으로 설정\r\n");
      out.write("		$(document).ready(function(){\r\n");
      out.write("			$(\".counttitlename\").on('keyup',function(){\r\n");
      out.write("				$(\".counttitlelength\").html(($(this).val().length+\" / 40\"));\r\n");
      out.write("				\r\n");
      out.write("				if($(this).val().length>40){\r\n");
      out.write("					alert(\"제목은 40자 이하로 적어주세요\")\r\n");
      out.write("					$(this).val($(this).val().substring(0, 40));\r\n");
      out.write("		            $('.counttitlelength').html(\"(40 / 40)\");\r\n");
      out.write("				}\r\n");
      out.write("			})\r\n");
      out.write("		})\r\n");
      out.write("		//내용 2000자 미만으로 설정\r\n");
      out.write("		$(document).ready(function(){\r\n");
      out.write("			$(\".contentWritePart\").on('keyup',function(){\r\n");
      out.write("				$(\".countContentlength\").html(($(this).val().length+\" / 2000\"));\r\n");
      out.write("				\r\n");
      out.write("				if($(this).val().length>2000){\r\n");
      out.write("					alert(\"제목은 40자 이하로 적어주세요\")\r\n");
      out.write("					$(this).val($(this).val().substring(0, 2000));\r\n");
      out.write("		            $('.countContentlength').html(\"(2000 / 2000)\");\r\n");
      out.write("				}\r\n");
      out.write("			})\r\n");
      out.write("		})\r\n");
      out.write("	\r\n");
      out.write("	</script>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("    <!DOCTYPE html>\r\n");
      out.write("    <html lang=\"en\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("        <title>Document</title>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"../../resources/css/common/common.css\">\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        <footer id=\"footer\">\r\n");
      out.write("            <div id=\"footer_content\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <span>발표시키지마시조</span>\r\n");
      out.write("                    |\r\n");
      out.write("                    <span>팀장 : 노한서</span>\r\n");
      out.write("                    |\r\n");
      out.write("                    <span>팀원 : 조현</span>\r\n");
      out.write("                    |\r\n");
      out.write("                    <span>팀원 : 김태연</span>\r\n");
      out.write("                    |\r\n");
      out.write("                    <span>팀원 : 최윤종</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <span>세미 프로젝트</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <span>노한서(팀장) : </span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <span>조현 : </span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <span>김태연 : </span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <span>최윤종 : </span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <span>Copyright © 2022.02.22-2022.04.03 KH Information Educational Institute All Right Reserved</span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"logo\"><a href=\"/\"><img src=\"../../resources/images/logo.gif\" alt=\"로고이미지\"></a></div>\r\n");
      out.write("        </footer>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("        <script src=\"../../resources/library/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("        <script src=\"../../resources/js/common/common.js\"></script>\r\n");
      out.write("    </body>\r\n");
      out.write("    </html>");
      out.write("\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.5.1.js\" integrity=\"sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
